on:
  workflow_call:
   secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASS:
        required: true
      DOCKER_REPO:
        required: true
   inputs:
      
      runnerName:
        required: true
        default: "ubuntu-latest"
        type: string
jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ${{ inputs.runnerName }}
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
           java-version: 11.0.4
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Build Docker image
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker image
          run: docker push $REPO
    
        - name: Image Scan
          uses: aquasecurity/trivy-action@master
          with:
           image-ref: $REPO
           security-checks: 'vuln,secret,config'
           format: 'sarif'
           output: 'trivy-image-results.sarif'
           severity: 'CRITICAL,HIGH'
          
        - name: Upload the scan result to GitHub Security
          uses: github/codeql-action/upload-sarif@v2
          with:
           sarif_file: 'trivy-image-results.sarif'
           category: 'image'
        
